### PR TITLE
Nonstationary and threshold models 

### PR DESCRIPTION
**Pull request by ericward-noaa**
These fixes make the threshold models and non-stationary models compatible with the changes incorporating the delta families. All tests passing.

These changes assume the same form (e.g. logistic, breakpoint) for both components of delta models still -- something that can be fixed eventually if folks think that's a useful feature? Or ability to estimate a threshold in just 1 component?

### CODE REVIEW

**Review by seananderson — COMMENTED** [review]
Thanks for this! Existing tests seem to be passing and the code looks reasonable to me. Two things:

1. tidy() and hence print() won't work yet for delta models with threshold covariates (after removing the current stop().

2. perhaps more importantly, will there ever be a time when the binomial model will fit with a threshold covariate? I can't seem to simulate one I can fit and I'm not sure there's that much information in 0-1 data. Might a more usable option be to just put the threshold covariates in the positive component? In that case, the dimension of the threshold covariates would be reduced again and that would simplify the print() issue.

See this unit test: https://github.com/pbs-assess/sdmTMB/blob/4f9d5748d12cb66c5ec00857710bb5cefc7c7513/tests/testthat/test-threshold-models.R#L33-L84

**Comment by ericward-noaa** [comment]
Yeah -- I think it's possible to estimate a threshold with binomial data. I just increased the spatial variance / mesh resolution (that does ok -- but replicating observations does even better)

set.seed(1) 
predictor_dat <- data.frame( 
  X = runif(10000), Y = runif(10000), 
  a1 = rnorm(10000) 
) 
mesh <- make_mesh(predictor_dat, xy_cols = c("X", "Y"), cutoff = 0.05) 
s1 <- sdmTMB_simulate( 
  formula = ~ 1 + breakpt(a1), 
  data = predictor_dat, 
  mesh = mesh, 
  family = binomial(), 
  range = 0.5, 
  phi = 0.001, 
  sigma_O = 0.2, 
  seed = 42, 
  B = 0, 
  threshold_coefs = c(0.5, 1) 
) 
s1$a1 <- predictor_dat$a1
fit <- sdmTMB(observed ~ -1+breakpt(a1),
              data = s1,
              family = binomial(),
              mesh = mesh)

s2 <- sdmTMB_simulate( 
  formula = ~ 1 + breakpt(a1), 
  data = predictor_dat, 
  mesh = mesh, 
  family = binomial(), 
  range = 0.5, 
  phi = 0.02, 
  sigma_O = 0.2, 
  seed = 42, 
  B = 0, 
  threshold_coefs = c(0.5, 1) 
) 
s2$a1 <- predictor_dat$a1

# replicate observations
s <- rbind(s1, s2)
mesh <- make_mesh(s, xy_cols = c("X", "Y"), cutoff = 0.05) 
fit <- sdmTMB(observed ~ -1+breakpt(a1),
              data = s,
              family = binomial(),
              mesh = mesh)

**Comment by seananderson** [comment]
Hmm, indeed, binomial and Gamma models fit just fine. But delta_gamma() ones consistently aren't fitting. I haven't been able to figure out why yet. See this unit test: https://github.com/pbs-assess/sdmTMB/blob/faa938884c7d46b4b11bd45a4f1a1ec38ce6d523/tests/testthat/test-threshold-models.R#L79-L98

**Comment by seananderson** [comment]
Found it, there was a typo here where the linear predictor array was always indexed by the first delta column: https://github.com/pbs-assess/sdmTMB/pull/108/commits/3c9523faa142ae9751203e1b70fc2a19c629d8c0

**Pull request merged**
