### PR TITLE
add CAIC and EDF calcs

### PR DESCRIPTION
**Pull request by James-Thorson-NOAA**
adding function for conditional AIC (CAIC) and effective degrees of freedom (EDF), thanks to new derivation by Nan Zheng for generic calculation using AD+Laplace approximation methods in TMB

### CODE REVIEW

**Comment by James-Thorson** [comment]
@seananderson do you want me to look at this again?  As I said before, I'd still like an option for the EDF to be incorporated into the `print_one_model` output (similar to mgcv::summary),

**Comment by seananderson** [comment]
I've got as far as cleaning things up and passing all R CMD checks and I just incorporated the function into the main branch so it can be used. Getting the pretty printing working is going to take a chunk of time I haven't found yet, but I'll leave the other issue open until that's done. On top of splitting the smoother, time-varying random effect, and IID random effect groups, there's also the delta model dimension to consider. I'll start with the smoothers, which I already have some code lying around for.

**Comment by James-Thorson** [comment]
Awesome!  Please tell me if you want me to share how I distinguished the groups in demo code for `tinyVAST`.  

Also, I just realized that I had a bug in my various versions, and sorry for catching it now!  Specifically it should be `q <- sum(indx)` instead of `q <- length(indx)`.  Do you want me to do a quick PR?

**Comment by seananderson** [comment]
No problem. I've fixed the `q`/`indx` bug in the main branch.

> Please tell me if you want me to share how I distinguished the groups in demo code for tinyVAST.

Sure, I'll take any ideas!

**Pull request merged**
