### PR TITLE
Changes for visreg

### PR DESCRIPTION
**Pull request by ericward-noaa**
I created a separate branch for this because the checks were driving me a bit crazy. This is 2 changes

1. I commented out the test for mesh$n to be exact -- early on we had the test returning a value of 141, but that was commented out and changed to 150. Now, I get the test returning 141 again. My version info is pasted below (note: OpenMP not installed on this computer)

3. Add in things for predict() to work with visreg: these are 2 minor changes to predict() to get everything working with the version of visreg on my branch. 

These build cleanly locally with a single note on package size. 

               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          1.3                         
year           2022                        
month          03                          
day            10                          
svn rev        81868                       
language       R                           
version.string R version 4.1.3 (2022-03-10)
nickname       One Push-Up

### CODE REVIEW

**Comment by ericward-noaa** [comment]
Here's it building cleanly locally
image
image

**Comment by ericward-noaa** [comment]
I think the cause of this is that predict(), residuals() etc are throwing warnings when OpenMP isn't supported -- and causing vignettes all to fail. This warning gets thrown: 

Warning in TMB::openmp(NULL) : OpenMP not supported.

**Comment by seananderson** [comment]
Not sure what's going on, but my 2 test commits above checked just fine and yours failed again with `polygon edge not found`. 

E.g. https://github.com/pbs-assess/sdmTMB/pull/76/commits/2ec0179e0a17007770d60958f0a98de08721aeca

**Comment by seananderson** [comment]
Perhaps you hadn't pulled my 'tidying' commit and that somehow fixed it.

**Comment by ericward-noaa** [comment]
Yeah -- I pulled with your tidy update, and looks like the polygon thing is still happening in vignettes. This certainly could be a GH CI thing, so maybe I'll wait to do anything here for a few days. But if not I think the problem is in the sys.calls() line -- 

see the difference in this commit 
https://github.com/pbs-assess/sdmTMB/pull/76/commits/0e1365a4948253f5251c465568fc80f2b61ebd19

**Comment by ericward-noaa** [comment]
This polygon edge thing seems to be related to fonts and ggplot: 
https://www.programmingr.com/r-error-messages/error-in-grid-callc_textbounds-as-graphicsannotxlabel-xx-xy-polygon-edge-not-found/#:~:text=callc%20textbounds%2C%20as.-,graphicsannot(x%24label)%2C%20x%24x%2C%20x,call%20to%20the%20correct%20location.

And the setup of R on the CI testing side seems to be probably the issue. Here's an example from Bioconductor

https://www.mail-archive.com/bioc-devel@r-project.org/msg14115.html

**Comment by ecophilina** [comment]
visreg isn't working for me when I install the visreg branch: 
Screen Shot 2022-03-28 at 12 00 04 PM

Or when I use load_all:
Screen Shot 2022-03-28 at 12 04 15 PM

**Comment by seananderson** [comment]
Yes, you'll currently need Eric's fork of visreg. https://github.com/ericward-noaa/visreg We might be able to work around that.

**Comment by ericward-noaa** [comment]
I think it's because in visreg, there's the stats::get_all_vars() function that returns parameters in the model frame. My branch just add a step of adding X and Y back on within visreg. I think this is ok because the visreg source has similar modifications for maybe ~ 8-10 other packages

**Comment by seananderson** [comment]
It's fine, but I think we want predict() to work without x and y if it's a
prediction without random fields anyways. This is also needed so a model
fitted without random fields can predict without x and y.

**Comment by ericward-noaa** [comment]
no more changes here -- I'm putting gratia stuff on a new branch

**Comment by seananderson** [comment]
I'm closing this, because it's been pulled over into the delta branch piece by piece and is working there. Should be working with the CRAN visreg version.

**Pull request closed without merging**
