### PR TITLE
Doc some warning and stop messages

### PR DESCRIPTION
**Pull request by kellijohnson-NOAA**
Use \n to wrap some warning and stop messages in `predict()` and change since to because. Super trivial stuff that can be ignored if you don't want to accept the pull request. Just things I noticed over the last few days while trying to work with {sdmTMB}. Please let me know if there is a better way to do this in the future too. For example, I could just make a comment on the line in the file to note things or make an issue with line numbers.

### CODE REVIEW

**Comment by seananderson** [comment]
Thanks @kellijohnson-NOAA. I'm curious what I can test this in because in RStudio or in Terminal consoles on a Mac, stop, warning, and message all get wrapped for me. As an alternative that doesn't depend on hard wraps, I've tried some small helper functions over in the 'delta' branch: https://github.com/pbs-assess/sdmTMB/blob/3af447f612b4e858f8eeb309d8fbcf1fde52f6af/R/utils.R#L278-L288

Can you test these for me? Try:

```r
test_stop <- function(...) {
  stop(strwrap(paste0(...), prefix = " ", initial = ""), call. = FALSE)
}

msg <- paste0("This is a long message that goes on and on. ",
"This is a long message that goes on and on. ",
"This is a long message that goes on and on. ",
"This is a long message that goes on and on.")

stop(msg)
test_stop(msg)
rlang::inform(msg)
rlang::warn(msg)
rlang::abort(msg)
```

As for pull requests: go for it! It's probably best if you work off the 'delta' branch right now though, because it's so far ahead of 'main' and will be merged in soon.

**Comment by seananderson** [comment]
Just coming back to this. Do any of the rlang or cli package versions of inform, warn, and abort wrap for you, @kellijohnson-NOAA ?

**Comment by kellijohnson-NOAA** [comment]
Thanks @seananderson for bringing this back up to the top of my inbox. 

Some of the error messages, i.e., `stop()`, and the `rlang::...()` break mid-word which is awkward. Then, `test_stop()` in Visual Studio Code led to a letter being removed but this did not happen when running directly in Rterm.

Below is the output in Visual Studio Code.
image

**Comment by kellijohnson-NOAA** [comment]
We can just close this pull request and we can go with whatever you had in the delta branch.

**Comment by seananderson** [comment]
Thanks! So, if I’m reading that right, it looks like the cli package
versions work well. They wrap and they don’t break words up.

**Comment by kellijohnson-NOAA** [comment]
Yes, {cli} appears to be the winner.

**Comment by seananderson** [comment]
OK, delta branch now uses the cli abort/warn/inform functions throughout. I'll merge delta into main shortly.

**Pull request closed without merging**
